services:
  db:
    image: postgres:16
    container_name: tarjeteando_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tarjeteando
    ports:
      - "5432:5432"
    volumes:
      - tarjeteando_pg:/var/lib/postgresql/data

volumes:
  tarjeteando_pg:
